apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
      - name: database-app
        image: database-springboot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
